### Contacto con ADMIN
POST http://localhost:3001/contact/message/
Content-Type: application/json

{
  "name": "Martin Lamacchia",
  "email": "martinjiro22@gmail.com",
  "message": "Hola Administrador tengo un problema con la creacion del proyecto"
}

### Obtener todos los Usuarios
GET http://localhost:3001/user

### Crear un Usuario
POST http://localhost:3001/user/register
Content-Type: application/json

{
  "name": "Martin",
  "lastName": "Lamacchia",
  "userName": "Zurdo666",
  "technologies": ["JavaScript", "HTML", "CSS", "NodeJS", "React"],
  "email": "martinjiro22@gmail.com",
  "password": "Pass123",
}

### Crear un Proyecto
POST http://localhost:3001/proyect/create
Content-Type: application/json

{
  "name": "Ecomerce Indumentaria",
  "description": "Tenermos que hacer un Ecomerce de ropa donde tenga un stock",
  "technologies": ["JavaScript", "HTML", "CSS", "NodeJS", "React"],
  "linkProyectBack": "",
  "linkProyectFront": "",
  "image": "",
  "createdBy": "65699972af200167f47502aa" 
}

### Obtener todos los Proyectos
GET http://localhost:3001/project

### Obtener un proyecto por Id
GET http://localhost:3001/proyect/6573addf59580384f620cf02

### Registrarse a un Proyecto
POST http://localhost:3001/proyect/register
Content-Type: application/json

{
  "proyectId": "65737acdbfed0f4cb263cc79",
  "participantsId": "656a5956109780b90cd3cabc"
}

### Borrar usuario de un Proyecto
POST http://localhost:3001/proyect/deleteUser
Content-Type: application/json

{
  "proyectId": "65737acdbfed0f4cb263cc79",
  "participantsId": "656a54d2df516ba1622d5c41"
}

### Borrar usuario de un Proyecto
DELETE http://localhost:3001/proyect/deleteProyect/6573b309f70a83ebfab68cc6

### Invitar usuario de un Proyecto
POST http://localhost:3001/project/invite
Content-Type: application/json

{
  "projectId": "657579d9841501018808ccd6",
  "inviteUsers": ["657535de8f80c591de8c4c7a", "6575707379ea90729e75f6c1", "657b881d45a1691d99af86f7"]
}